### ISSUE TITLE
Brainstorming

### ISSUE THREAD

**Issue by marcusstenbeck** [alexung/angular-talkey#12]
These are my random raw thoughts on what's supposed to go in. I think the most important thing is the talks, and secondly the people, meetups/confs are the least important in my mind since what we're trying to connect people to is good talks (and that could be people looking to see talks too). Do you agree/disagree?

![Brainstorm](http://s23.postimg.org/vicg5ffwb/Screenshot_2015_06_01_06_59_10.png)

**Comment by marcusstenbeck** [comment]
@alexung Do you get messages about issues when I don't tag your name?

**Comment by marcusstenbeck** [comment]
Test without tag.

**Comment by alexung** [comment]
Yeah i do

On Mon, Jun 1, 2015 at 8:39 AM, Marcus Stenbeck notifications@github.com
wrote:

> Test without tag.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alexung/angular-talkey/issues/12#issuecomment-107591491
> .

## 

_Alex Ung_ | Software Engineer
phone: (714) 683-6517
lync / email: alex.ung@accenture.com
_Accenture_

**Comment by marcusstenbeck** [comment]
Cool. Take a look at this and let me know if you have any concerns with it.
